"""added quantidade

Revision ID: 0df9eb965b64
Revises: b58a49093a9a
Create Date: 2018-11-21 18:42:49.904563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df9eb965b64'
down_revision = 'b58a49093a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('quantidade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'quantidade')
    # ### end Alembic commands ###
