"""tables revisited

Revision ID: 31178b261aa0
Revises: 
Create Date: 2018-10-20 22:17:25.382668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31178b261aa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    op.drop_table('endereco')
    op.drop_table('cachorro')
    op.drop_table('contato')
    op.drop_table('venda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('data_venda', sa.DATE(), nullable=False),
    sa.Column('valor_venda', sa.NUMERIC(), nullable=False),
    sa.Column('valor_taxi', sa.NUMERIC(), nullable=False),
    sa.Column('n_banhos', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=6), nullable=False),
    sa.Column('pacote', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('forma_pagto', sa.VARCHAR(length=8), nullable=False),
    sa.Column('data_pagto', sa.DATE(), nullable=False),
    sa.Column('valor_entrada', sa.NUMERIC(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.Column('dog_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("forma_pagto IN ('cash', 'debito', 'credito', 'cheque', 'pendente')"),
    sa.CheckConstraint("tipo IN ('pacote', 'avulso')"),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['cachorro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contato',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tel1', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('tel2', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('email', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cachorro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('breed', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('pelagem', sa.VARCHAR(length=5), nullable=False),
    sa.Column('nascimento', sa.DATE(), nullable=True),
    sa.Column('data_start', sa.DATE(), nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=1), nullable=False),
    sa.Column('castrado', sa.VARCHAR(length=1), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("castrado IN ('S', 'N')"),
    sa.CheckConstraint("pelagem IN ('longo', 'curto')"),
    sa.CheckConstraint("sexo IN ('M', 'F')"),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rua', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('numero', sa.INTEGER(), nullable=True),
    sa.Column('bairro', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cidade', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('estado', sa.CHAR(length=2), nullable=True),
    sa.Column('distancia', sa.NUMERIC(), nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('sexo', sa.VARCHAR(length=1), nullable=False),
    sa.CheckConstraint("sexo IN ('M', 'H')"),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
