"""here we go

Revision ID: 553fe7247fea
Revises: 
Create Date: 2018-10-27 19:17:20.212176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553fe7247fea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'H'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel1', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('tel2', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('email', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('bairro', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cidade', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('estado', sa.CHAR(length=2), nullable=True),
    sa.Column('distancia', sa.Numeric(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peludo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('breed', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('pelagem', sa.Enum('longo', 'curto'), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('data_start', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F'), nullable=False),
    sa.Column('castrado', sa.Enum('S', 'N'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('valor_venda', sa.Numeric(), nullable=False),
    sa.Column('valor_taxi', sa.Numeric(), nullable=False),
    sa.Column('n_banhos', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.Enum('pacote', 'avulso'), nullable=False),
    sa.Column('pacote', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('forma_pagto', sa.Enum('cash', 'debito', 'credito', 'cheque', 'pendente'), nullable=False),
    sa.Column('data_pagto', sa.Date(), nullable=False),
    sa.Column('valor_entrada', sa.Numeric(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('peludo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['peludo_id'], ['peludo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda')
    op.drop_table('peludo')
    op.drop_table('endereco')
    op.drop_table('contato')
    op.drop_table('cliente')
    # ### end Alembic commands ###
