"""here we go-plural

Revision ID: 57a27f0be18e
Revises: 553fe7247fea
Create Date: 2018-10-27 19:28:44.926704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a27f0be18e'
down_revision = '553fe7247fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'H'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel1', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('tel2', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('email', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('bairro', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cidade', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('estado', sa.CHAR(length=2), nullable=True),
    sa.Column('distancia', sa.Numeric(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peludos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('breed', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('pelagem', sa.Enum('longo', 'curto'), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('data_start', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F'), nullable=False),
    sa.Column('castrado', sa.Enum('S', 'N'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('valor_venda', sa.Numeric(), nullable=False),
    sa.Column('valor_taxi', sa.Numeric(), nullable=False),
    sa.Column('n_banhos', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.Enum('pacote', 'avulso'), nullable=False),
    sa.Column('pacote', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('forma_pagto', sa.Enum('cash', 'debito', 'credito', 'cheque', 'pendente'), nullable=False),
    sa.Column('data_pagto', sa.Date(), nullable=False),
    sa.Column('valor_entrada', sa.Numeric(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('peludo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['peludo_id'], ['peludos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contato')
    op.drop_table('endereco')
    op.drop_table('peludo')
    op.drop_table('cliente')
    op.drop_table('venda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('data_venda', sa.DATE(), nullable=False),
    sa.Column('valor_venda', sa.NUMERIC(), nullable=False),
    sa.Column('valor_taxi', sa.NUMERIC(), nullable=False),
    sa.Column('n_banhos', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=6), nullable=False),
    sa.Column('pacote', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('forma_pagto', sa.VARCHAR(length=8), nullable=False),
    sa.Column('data_pagto', sa.DATE(), nullable=False),
    sa.Column('valor_entrada', sa.NUMERIC(), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.Column('peludo_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("forma_pagto IN ('cash', 'debito', 'credito', 'cheque', 'pendente')"),
    sa.CheckConstraint("tipo IN ('pacote', 'avulso')"),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['peludo_id'], ['peludo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('sexo', sa.VARCHAR(length=1), nullable=False),
    sa.CheckConstraint("sexo IN ('M', 'H')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peludo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('breed', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('pelagem', sa.VARCHAR(length=5), nullable=False),
    sa.Column('nascimento', sa.DATE(), nullable=True),
    sa.Column('data_start', sa.DATE(), nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=1), nullable=False),
    sa.Column('castrado', sa.VARCHAR(length=1), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("castrado IN ('S', 'N')"),
    sa.CheckConstraint("pelagem IN ('longo', 'curto')"),
    sa.CheckConstraint("sexo IN ('M', 'F')"),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rua', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('numero', sa.INTEGER(), nullable=True),
    sa.Column('bairro', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cidade', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('estado', sa.CHAR(length=2), nullable=True),
    sa.Column('distancia', sa.NUMERIC(), nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contato',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tel1', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('tel2', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('email', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vendas')
    op.drop_table('peludos')
    op.drop_table('enderecos')
    op.drop_table('contatos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
