"""3rd cmt

Revision ID: a60850c771b0
Revises: 
Create Date: 2018-09-30 18:41:31.180284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60850c771b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cachorro')
    op.drop_table('cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('sexo', sa.VARCHAR(length=1), nullable=False),
    sa.CheckConstraint("sexo IN ('M', 'H')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cachorro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('breed', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('pelagem', sa.VARCHAR(length=5), nullable=False),
    sa.Column('idade', sa.INTEGER(), nullable=True),
    sa.Column('data_start', sa.DATE(), nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=1), nullable=False),
    sa.Column('castrado', sa.VARCHAR(length=1), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("castrado IN ('S', 'N')"),
    sa.CheckConstraint("pelagem IN ('longo', 'curto')"),
    sa.CheckConstraint("sexo IN ('M', 'F')"),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
