"""first commit

Revision ID: c586df2fc8f5
Revises: 
Create Date: 2018-11-04 21:02:53.708400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c586df2fc8f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'H'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel1', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('tel2', sa.NVARCHAR(length=13), nullable=True),
    sa.Column('email', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('bairro', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('cidade', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('estado', sa.CHAR(length=2), nullable=True),
    sa.Column('distancia', sa.Float(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peludos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=30), nullable=False),
    sa.Column('breed', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('pelagem', sa.Enum('longo', 'curto'), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('data_start', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F'), nullable=False),
    sa.Column('castrado', sa.Enum('S', 'N'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas_cur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('valor_servicos', sa.Float(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas_prod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas_bt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('data_pbanho', sa.Date(), nullable=False),
    sa.Column('valor_servicos', sa.Float(), nullable=False),
    sa.Column('valor_taxi', sa.Float(), nullable=False),
    sa.Column('n_banhos', sa.Integer(), nullable=False),
    sa.Column('tipo_banho', sa.Enum('pacote', 'avulso', 'cortesia'), nullable=False),
    sa.Column('pacote', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('peludo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['peludo_id'], ['peludos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas_hot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=False),
    sa.Column('valor_diarias', sa.Float(), nullable=False),
    sa.Column('valor_servicos', sa.Float(), nullable=False),
    sa.Column('valor_taxi', sa.Float(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('peludo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['peludo_id'], ['peludos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('valor_entrada', sa.Float(), nullable=False),
    sa.Column('forma_pagto', sa.Enum('cash', 'debito', 'credito', 'cheque', 'pendente'), nullable=False),
    sa.Column('venda_bt_id', sa.Integer(), nullable=True),
    sa.Column('venda_hot_id', sa.Integer(), nullable=True),
    sa.Column('venda_cur_id', sa.Integer(), nullable=True),
    sa.Column('venda_pro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venda_bt_id'], ['vendas_bt.id'], ),
    sa.ForeignKeyConstraint(['venda_cur_id'], ['vendas_cur.id'], ),
    sa.ForeignKeyConstraint(['venda_hot_id'], ['vendas_hot.id'], ),
    sa.ForeignKeyConstraint(['venda_pro_id'], ['vendas_prod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('vendas_hot')
    op.drop_table('vendas_bt')
    op.drop_table('vendas_prod')
    op.drop_table('vendas_cur')
    op.drop_table('peludos')
    op.drop_table('enderecos')
    op.drop_table('contatos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
