"""added saldo

Revision ID: f92679e66335
Revises: d55be76a2835
Create Date: 2018-11-15 15:00:15.074860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92679e66335'
down_revision = 'd55be76a2835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('saldo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'saldo')
    # ### end Alembic commands ###
